name: NeryByService CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, ARM64]
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy Docker Compose
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          IP_LOCATE_KEY: ${{ secrets.IP_LOCATE_KEY }}
          AWS_REGION: "us-east-1"
          BEDROCK_MODEL_ID: "us.amazon.nova-lite-v1:0"
        run: |
          docker compose pull || true
          docker compose up --build -d
